spring.application.name=adoption-center

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/adoption_center
spring.datasource.username=adoption_user
spring.datasource.password=adoption_pass123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.graphql.graphiql.enabled=true
spring.graphql.http.path=/graphql
